### ISSUE TITLE
Craft tries to send a notification even if the criteria is not met

### ISSUE THREAD

**Issue by Saboteur777** [percipioglobal/craft-notifications#19]
**notifications.php**
```
return [
    'notifications' => [
        [
            'class' => \craft\elements\Entry::class,
            'event' => \craft\elements\Entry::EVENT_AFTER_SAVE,
            'criteria' => [
                'section' => 'channelReservations'
            ],
            'notification' => \app\notifications\TableReservationReceivedAdmin::class,
        ]
    ],
];
```

I have to guard it with an additional conditional in notifications/NotificationName.php:

**notifications/NotificationName.php**
```
    public function via()
    {
        $entry = $this->event->sender;
        $queryEmail = $entry->queryEmail;

        if ($this->event->isNew && $entry->section === 'channelReservations') {
            return [
                'mail' => $queryEmail,
            ];
        }

        return [];
    }
```

**Comment by JamesNuttall** [comment]
Im experiencing the same issue here.

I believe some sort of guard like the one @Saboteur777 has implemented is needed in the root [notifications.php file](https://github.com/Rias500/craft-notifications/blob/master/src/Notifications.php#L88) when the events for each configured notification are being registered.

I will submit a PR at some point today.

**Comment by pierrestoffe** [comment]
Same issue here. I'm relying on a condition within my toMail function instead.

**Comment by jedimonkey** [comment]
Probably could safely remove 'criteria' from the config.php file, there is no implementation that I can see in the source (partial or otherwise).

**Comment by cookie10codes** [comment]
Sorry for the late reply, we took this one in our Craft 4 release and we removed the criteria in the config file
