### ISSUE TITLE
Class `rias\notifications\models\Notification` not found after updating from 1.1.1 to 1.1.3 (change of ownership)

### ISSUE THREAD

**Issue by ademers** [percipioglobal/craft-notifications#62]
I was able to successfully update from 1.1.1. to 1.1.3. However, when submitting a front-end form that triggers an email notification, I got the above error. Screenshot https://share.getcloudapp.com/12uNg0zL

I changed the Class names from:

```
use rias\notifications\messages\SlackMessage;
use rias\notifications\models\Notification;
```
to 
```
use percipioglobal\notifications\messages\SlackMessage;
use percipioglobal\notifications\models\Notification;
```

In all my notification files, and, so far, all appears to be working as expected. Is there anything else I need to do to ensure the proper functioning of the plugin? Unless I've missed it, I didn't see anything in the docs re updating from 1.1.1 to 1.1.3.

Thanks!

**Comment by timkelty** [comment]
Same here – if you're changing namespaces that others are using, this really should have been a major version bump…that or add aliases.

**Comment by michtio** [comment]
@timkelty you're right we should've done one or both, I'll address the issues this week and do a minor release, we have plans for a next major release on this one, which will included:

- Notifications configured in the CP
- Enabling / Disabling of them ( if you do a huge resave and you post to Slack for example ) 
- And more
