### ISSUE TITLE
Error during composer installation having to do with 'Tightenco\Collect\Support\Debug\Dumper'

### ISSUE THREAD

**Issue by brimby** [percipioglobal/craft-notifications#63]
I'm at the installation phase still. After running `composer require percipioglobal/craft-notifications` I'm getting the error `[ErrorException] Class 'Tightenco\Collect\Support\Debug\Dumper' not found` in my terminal.

**Comment by brimby** [comment]
Unrelated

**Comment by johnwbaxter** [comment]
@brimby What was it? I've got the same issue and I have no idea why this is happening!!
