### ISSUE TITLE
Argument #1 ($notifiable) must be of type string, null given

### ISSUE THREAD

**Issue by duncanmcclean** [percipioglobal/craft-notifications#72]
I've installed this plugin recently to send confirmation emails to users when they signup for an event - which is working fine.

However, I just went to make a content update on the site and realised that I receive an exception when I try - even though it's not an entry in the related 'section'

Here's our config:

```php
'notifications' => [
        [
            'class' => \craft\elements\Entry::class,
            'event' => \craft\elements\Entry::EVENT_AFTER_SAVE,
            'criteria' => [
                'section' => 'registration',
            ],
            'notification' => RegisteredForHighFive::class,
        ],
],
```

And here's the exception that's thrown when updating entries in the Admin/CP:

```
percipioglobal\notifications\channels\MailChannel::send(): Argument #1 ($notifiable) must be of type string, null given, called in /Users/duncan/Sites/sitename/vendor/percipioglobal/craft-notifications/src/services/NotificationsService.php on line 104
```

`registration` is the name of the section the event registrations are going into & `blog` is the section I'm trying to make updates to (but also happens on other sections).

I'm having to disable this plugin for now. Confirmation emails are really just a nice to have but I would really like to have them sorted.

**Comment by cookie10codes** [comment]
hi @duncanmcclean,

We've updated the config file with the new  Craft 4 release. Defining 'criteria' is now deprecated.

You'll need to provide the section check within the via function in RegisteredForHighFive.php. An example below to add a section to the check

```
    public function via(): array
    {
        $entry = $this->event->sender;

        if ($entry->section->handle === 'blog' && !$this->event->isNew) {
            return [
                'mail' => 'stefanie@percipio.london',
            ];
        }

        return [];
    }
```

Let me know if this fixed your bug.

Thanks,
Stefanie

**Comment by duncanmcclean** [comment]
Thanks @cookie10codes, that seems to work!
