### ISSUE TITLE
Error running the make command wondering if it is related to the namespace change?

### ISSUE THREAD

**Issue by laurabennett** [percipioglobal/craft-notifications#81]
./craft notifications/make MemberAdded

PHP Warning 'yii\base\ErrorException' with message 'file_get_contents(/home/nhvegberry/webapps/nhvegberry-dev/vendor/percipiolondon/craft-notifications/src/notification.stub): Failed to open stream: No such file or directory'

in /home/nhvegberry/webapps/nhvegberry-dev/vendor/percipioglobal/craft-notifications/src/console/controllers/MakeController.php:122

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /home/nhvegberry/webapps/nhvegberry-dev/vendor/percipioglobal/craft-notifications/src/console/controllers/MakeController.php(122): file_get_contents()
#2 /home/nhvegberry/webapps/nhvegberry-dev/vendor/percipioglobal/craft-notifications/src/console/controllers/MakeController.php(83): percipiolondon\notifications\console\controllers\MakeController->buildClass()
#3 [internal function]: percipiolondon\notifications\console\controllers\MakeController->actionIndex()
#4 /home/nhvegberry/webapps/nhvegberry-dev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#5 /home/nhvegberry/webapps/nhvegberry-dev/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#6 /home/nhvegberry/webapps/nhvegberry-dev/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#7 /home/nhvegberry/webapps/nhvegberry-dev/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#8 /home/nhvegberry/webapps/nhvegberry-dev/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#9 /home/nhvegberry/webapps/nhvegberry-dev/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction()
#10 /home/nhvegberry/webapps/nhvegberry-dev/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#11 /home/nhvegberry/webapps/nhvegberry-dev/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest()
#12 /home/nhvegberry/webapps/nhvegberry-dev/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest()
#13 /home/nhvegberry/webapps/nhvegberry-dev/craft(22): yii\base\Application->run()

**Comment by cookie10codes** [comment]
Hi @laurabennett,

Can you provide me the details of your Craft install and plugin version? This can be found in Utilities -> System Report

**Comment by laurabennett** [comment]
Craft Pro 4.3.5
Notifications 4.0.0

**Comment by cookie10codes** [comment]
@laurabennett Thank you for returning.

Can you verify if the notirifaction.stub exists on the path you've send please? Everything seems to be normal and working on my end. 

In which environment are you running your project from? I'm running my project inside of Docker

**Comment by laurabennett** [comment]
For one thing it says its looking in dev/vendor/percipiolondon but my vendor directory only has percipoglobal. I see there is a 4.1.0 now, I'll see if that makes any difference.

**Comment by cookie10codes** [comment]
That will be the issue, @laurabennett are you in the ability to re-install the plugin? if not, I'll check to create a migration within the plugin that does the namespace update for you

**Comment by laurabennett** [comment]
I can reinstall but this is what is available in the Craft Plugin Store. Do I just change my composer.json file to 
    "percipiolondon/craft-notifications": "4.1.0" ?


ddev composer require percipioglobal/craft-notifications -w && ddev craft plugin/install notifications
composer require percipioglobal/craft-notifications -w && php craft plugin/install notifications

**Comment by cookie10codes** [comment]
@laurabennett I see the mistake, I'm going to provide an update and release a version. I'll keep you posted when the update is there

**Comment by cookie10codes** [comment]
@laurabennett can you give 4.1.1 a spin please?

**Comment by laurabennett** [comment]
Great, it works. Thank you!

**Comment by cookie10codes** [comment]
Awesome! Thanks for your help @laurabennett, enjoy the plugin :-)!
