### ISSUE TITLE
Error on Notification

### ISSUE THREAD

**Issue by laurabennett** [percipioglobal/craft-notifications#82]
I'm following the documentation, maybe this is still related to the namespace change??

Declaration of app\notifications\MemberAdded::via() must be compatible with percipiolondon\notifications\models\Notification::via(): array

` in /home/nhvegberry/webapps/nhvegberry-dev/notifications/MemberAdded.phpat line 29
{
        parent::__construct($event);
    }
 
    /**
     * Get the notification's delivery channels.
     *
     * @return array
     */
    public function via()
    {
        return [
            'mail' => ['laura@drivebrandstudio.com'],
        ];
    }
 
    public function toDatabase()
    {
        return ArrayHelper::toArray($this);`

**Comment by cookie10codes** [comment]
@laurabennett can you add a returnary type to the via method like this:

```public function via(): array```

I'll update the .stub file where the php file is created from

**Comment by laurabennett** [comment]
Thanks!
